defmodule RiceWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :rice

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_rice_key",
    signing_salt: "BMDELOEl",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :rice,
    gzip: not code_reloading?,
    only: RiceWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :rice
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, {:multipart, length: 21 * 1024 * 1024}, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # 只给 /api 加 CORS。
  #
  # C 端 app 和 rice 不同源:app 在 xjdao.xyz,rice 在 rice.xjdao.xyz ——
  # 没有这些头,浏览器会把每一个 rice 请求都拦下来 —— 而且控制台不会有任何
  # 指向 CORS 的报错,表现只是整页空白。(xjdao 只有 web,没有原生 app。)
  #
  # 范围限定在 /api 是必要的,不是洁癖:`/session/:ticket` 那个交接接口
  # 自己写了一套 CORS 头,两边都写就会出现重复的 `Access-Control-Allow-Origin`,
  # 浏览器直接判定不合法。
  plug :cors_for_api
  plug RiceWeb.Router

  @cors_opts CORSPlug.init([])

  defp cors_for_api(%{request_path: "/api" <> _} = conn, _opts) do
    CORSPlug.call(conn, Keyword.put(@cors_opts, :origin, Rice.Cors.allowed_origins()))
  end

  defp cors_for_api(conn, _opts), do: conn
end
