import Config

# Configure your database
#
# `DATABASE_URL` 可以覆盖,用来连别的库(典型用法:SSH 隧道连测试环境的 rice_dev,
# `ssh -L 15432:127.0.0.1:5432`)。**本机和测试环境的库重名**,都叫 `rice_dev`,
# 不显式指定就会静悄悄地落在本机那个库上。
db_config =
  case System.get_env("DATABASE_URL") do
    # 空串当没设 —— `export DATABASE_URL=` 或者 `DATABASE_URL= mix …` 很常见,
    # 当成 url 的话报出来的是 "missing the :database key",看不出是这个原因
    url when url in [nil, ""] ->
      [username: "postgres", password: "postgres", hostname: "localhost", database: "rice_dev"]

    url ->
      [url: url]
  end

config :rice,
       Rice.Repo,
       db_config ++
         [
           stacktrace: true,
           show_sensitive_data_on_connection_error: true,
           pool_size: 10
         ]

# 指着别的库跑的时候,**不要在这台机器上起后台任务**。
#
# `:dev` 默认把 Oban 全开着,包括每分钟一次的结票 Cron。用 DATABASE_URL 指向
# 测试环境时,这台开发机就会变成那个库的一个 Oban 节点,替它结提案、过期任务 ——
# 而人在本机,根本不会去看那边的日志。
#
# 判据就用 DATABASE_URL 有没有设:设了就意味着"这不是我自己的库"。
if System.get_env("DATABASE_URL") not in [nil, ""] do
  config :rice, Oban, queues: false, plugins: false
end

# 开发环境:放行本机任意端口。
#
# 不写死端口是有原因的 —— social-app 的 web 版由 webpack 服务在 19006,
# 而 Expo 自己的 dev server 在 8081,日志里两个端口都会出现;端口被占时
# 还会自动换一个。写死一串端口的结果是:页面能打开、请求全被浏览器拦掉、
# 界面只是一片空白,没有任何报错指向 CORS。
#
# 只在 dev 这么松。生产走 CORS_ORIGINS 白名单,见 config/runtime.exs。
config :rice, :cors, origins: [~r{^http://(localhost|127\.0\.0\.1)(:\d+)?$}]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :rice, RiceWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "9Vl82/up1bnt+RvGpOm+Q4c9RiHg9rhyV87l3HZIlvVyMLwy3uyK42P2KBVLsdtr",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:rice, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:rice, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :rice, RiceWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/rice_web/router\.ex$"E,
      ~r"lib/rice_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :rice, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
